--INSERT INTO books (authorName, authorsurname, title, printyear) VALUES ('Barbara', 'Rosiek', 'Kokaina', 1985);
INSERT INTO books (authorName, authorsurname, title, printyear) VALUES ('Barbara', 'Rosiek', 'Skazana', 2008);
INSERT INTO books (authorName, authorsurname, title, printyear) VALUES ('Barbara', 'Rosiek', 'Byłam schizofreniczką', 2003);
INSERT INTO books (authorName, authorsurname, title, printyear) VALUES ('Adam', 'Nowak', 'Fala', 1997);
INSERT INTO books (authorName, authorsurname, title, printyear) VALUES ('Katarzyna', 'Olszewska', 'Krwawe powroty', 1999);
INSERT INTO books (authorName, authorsurname, title, printyear) VALUES ('Danuta', 'Podjacka', 'Zatruta miłość', 1979);
INSERT INTO books (authorName, authorsurname, title, printyear) VALUES ('Gabriel', 'Nakielski', 'Dżem i kwiaty', 2006);
INSERT INTO books (authorName, authorsurname, title, printyear) VALUES ('Miłosz', 'Hinc', 'Bambusowe dni', 2014);
INSERT INTO books (authorName, authorsurname, title, printyear) VALUES ('Fabian', 'Kowalski', 'Wakacyjny domek', 2017);
INSERT INTO books (authorName, authorsurname, title, printyear) VALUES ('Katarzyna', 'Marchiewicz', 'Słoneczne pocałunki', 2010);