spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    generate-ddl: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/oro
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver
  security:
      user:
        name: andrzej
        password: admin

server:
  port: 8080
  servlet:
    context-path: /
    path: /

logging:
  level:
    org.springframework.web: ERROR
    dictionary: DEBUG
    # Hides HHH000424: Disabling contextual LOB creation as createClob() method threw error
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: WARN
#  pattern: